const LogType = {
    Normal: 1,
    UserCreated: 2,
    Partition: 3,
    UnlockPractice: 4,
    CreateChapter: 5,
    UpdateChapter: 6,
    DeleteChapter: 7,
    CreateBeacon: 8,
    DeactivateBeacon: 9,
    CreateBeaconActivity: 10,
    UpdateBeaconActivity: 11,
    UpdateUser: 12,
    DeleteUser: 13,
    CreateOne: 14,
    UpdateOne: 15,
    DeleteOne: 16,
    CreateGospelStep: 17,
    UpdateGospelStep: 18,
    DeleteGospelStep: 19,
    CreateOneNote: 20,
    UpdateOneNote: 21,
    DeleteOneNote: 22,
    CreateChristian: 23,
    UpdateChristian: 24,
    DeleteChristian: 25,
    UpdateActionSteps: 26,
    RefreshTokens: 27,
    CreateGlobalBeacon: 28,
    CreateGlobalBeaconActivity: 29,
    UpdateGlobalBeaconActivity: 30,
};

// README: If you want to change, please also change enums.tsx in the gospel-initiative client project.
const GlobalBeaconType = {
    None: 0,
    NewBelievers: 1,
    BoldnessToShare: 2,
    Missionaries: 3,
    MissionsTrips: 4,
    OurCity: 5,
    Neighborhood: 6,
    Schools: 7,
    PoorHungry: 8,
    Families: 9,
    Parents: 10,
    Marriages: 11,
    Nation: 12,
    Toddlers: 13,
    ElementarySchoolers: 14,
    MiddleSchoolers: 15,
    HighSchoolers: 16,
    Mosaic: 17,
    YoungAdults: 18,
    Elderly: 19,
    Workplaces: 20,
    Leaders: 21,
    Discipleship: 22,
    ChurchUnity: 23,
    AddictionRecovery: 24,
    LeadersInTraining: 25
}

module.exports = { LogType, GlobalBeaconType };