const LogType = {
    Normal: 1,
    UserCreated: 2,
    Partition: 3,
    UnlockPractice: 4,
    CreateChapter: 5,
    UpdateChapter: 6,
    DeleteChapter: 7,
    CreateBeacon: 8,
    DeactivateBeacon: 9,
    CreateBeaconActivity: 10,
    UpdateBeaconActivity: 11,
    UpdateUser: 12,
    DeleteUser: 13,
    CreateOne: 14,
    UpdateOne: 15,
    DeleteOne: 16,
    CreateGospelStep: 17,
    UpdateGospelStep: 18,
    DeleteGospelStep: 19,
    CreateOneNote: 20,
    UpdateOneNote: 21,
    DeleteOneNote: 22,
    CreateChristian: 23,
    UpdateChristian: 24,
    DeleteChristian: 25,
    CreateActionStep: 26,
    UpdateActionStep: 27
};

module.exports = { LogType };